# Generated by Django 4.1.3 on 2022-11-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_banner_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='price',
        ),
    ]
