# Generated by Django 4.1.3 on 2022-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_productattribute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
